"""update task model

Revision ID: f774f42cd7c6
Revises: 7954b6ae1357
Create Date: 2026-06-19 13:12:59.241217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f774f42cd7c6'
down_revision: Union[str, Sequence[str], None] = '7954b6ae1357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_members_ibfk_2'), 'project_members', type_='foreignkey')
    op.drop_constraint(op.f('project_members_ibfk_1'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               nullable=False)
    op.drop_constraint(op.f('tasks_ibfk_1'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_ibfk_2'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_ibfk_3'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_ibfk_3'), 'tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('tasks_ibfk_2'), 'tasks', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(op.f('tasks_ibfk_1'), 'tasks', 'users', ['assigned_user_id'], ['id'])
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_ibfk_1'), 'project_members', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_members_ibfk_2'), 'project_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
